// Generated by gencpp from file motion_planning/Direction.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_MESSAGE_DIRECTION_H
#define MOTION_PLANNING_MESSAGE_DIRECTION_H

#include <ros/service_traits.h>


#include <motion_planning/DirectionRequest.h>
#include <motion_planning/DirectionResponse.h>


namespace motion_planning
{

struct Direction
{

typedef DirectionRequest Request;
typedef DirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Direction
} // namespace motion_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_planning::Direction > {
  static const char* value()
  {
    return "91ac0cf00c7cda6ec66ed487aa4d6933";
  }

  static const char* value(const ::motion_planning::Direction&) { return value(); }
};

template<>
struct DataType< ::motion_planning::Direction > {
  static const char* value()
  {
    return "motion_planning/Direction";
  }

  static const char* value(const ::motion_planning::Direction&) { return value(); }
};


// service_traits::MD5Sum< ::motion_planning::DirectionRequest> should match
// service_traits::MD5Sum< ::motion_planning::Direction >
template<>
struct MD5Sum< ::motion_planning::DirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planning::Direction >::value();
  }
  static const char* value(const ::motion_planning::DirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planning::DirectionRequest> should match
// service_traits::DataType< ::motion_planning::Direction >
template<>
struct DataType< ::motion_planning::DirectionRequest>
{
  static const char* value()
  {
    return DataType< ::motion_planning::Direction >::value();
  }
  static const char* value(const ::motion_planning::DirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_planning::DirectionResponse> should match
// service_traits::MD5Sum< ::motion_planning::Direction >
template<>
struct MD5Sum< ::motion_planning::DirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planning::Direction >::value();
  }
  static const char* value(const ::motion_planning::DirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planning::DirectionResponse> should match
// service_traits::DataType< ::motion_planning::Direction >
template<>
struct DataType< ::motion_planning::DirectionResponse>
{
  static const char* value()
  {
    return DataType< ::motion_planning::Direction >::value();
  }
  static const char* value(const ::motion_planning::DirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_PLANNING_MESSAGE_DIRECTION_H
